events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    client_max_body_size 8M;

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://api:5000;  # Прокси на ваш API-сервис
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /grafana/ {
            proxy_pass http://grafana:3000/;  # Прокси на Grafana
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}